backend:
  name: github
  repo: nishiken-san/fork-website # あなたのGitHubリポジトリに変更
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# 日本語対応
locale: 'ja'

collections:
  # サイト設定
  - name: "settings"
    label: "サイト設定"
    files:
      - name: "general"
        label: "基本設定"
        file: "content/settings/site.json"
        fields:
          - {label: "サイト名", name: "title", widget: "string", default: "fork"}
          - {label: "キャッチフレーズ", name: "tagline", widget: "string"}
          - {label: "説明文", name: "description", widget: "text"}
          - label: "会社情報"
            name: "company"
            widget: "object"
            fields:
              - {label: "会社名", name: "name", widget: "string"}
              - {label: "メールアドレス", name: "email", widget: "string"}
              - {label: "電話番号", name: "phone", widget: "string"}
              - {label: "住所", name: "address", widget: "string"}

  # プロジェクト
  - name: "projects"
    label: "プロジェクト"
    folder: "content/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "スラッグ", name: "slug", widget: "string"}
      - {label: "説明", name: "description", widget: "string"}
      - {label: "メイン画像", name: "image", widget: "image"}
      - {label: "クライアント", name: "client", widget: "string"}
      - {label: "年", name: "year", widget: "number", value_type: "int"}
      - label: "カテゴリー"
        name: "category"
        widget: "select"
        options: ["ブランディング", "ウェブデザイン", "グラフィックデザイン", "コンサルティング"]
      - label: "タグ"
        name: "tags"
        widget: "list"
        field: {label: "タグ", name: "tag", widget: "string"}
      - {label: "公開", name: "published", widget: "boolean", default: true}
      - {label: "特集", name: "featured", widget: "boolean", default: false}
      - {label: "日付", name: "date", widget: "datetime"}
      - {label: "内容", name: "body", widget: "markdown"}

  # ニュース
  - name: "news"
    label: "ニュース"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "日付", name: "date", widget: "datetime"}
      - {label: "説明", name: "description", widget: "string"}
      - {label: "アイキャッチ画像", name: "image", widget: "image", required: false}
      - label: "カテゴリー"
        name: "category"
        widget: "select"
        options: ["お知らせ", "プロジェクト", "イベント", "コラム"]
      - {label: "公開", name: "published", widget: "boolean", default: true}
      - {label: "内容", name: "body", widget: "markdown"}

  # ページ設定
  - name: "pages"
    label: "ページ"
    files:
      - name: "home"
        label: "トップページ"
        file: "content/pages/home.json"
        fields:
          - {label: "タイトル", name: "title", widget: "string"}
          - {label: "メインキャッチコピー", name: "heroTitle", widget: "string"}
          - {label: "サブキャッチコピー", name: "heroSubtitle", widget: "string"}
          - label: "About セクション"
            name: "about"
            widget: "object"
            fields:
              - {label: "タイトル", name: "title", widget: "string"}
              - {label: "内容", name: "content", widget: "markdown"}

# エディター設定
editor:
  preview: true